# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'thinkitive-text-animator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for thinkitive-text-animator

  target 'thinkitive-text-animatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'thinkitive-text-animatorUITests' do
    # Pods for testing
  end

end
