# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'thinkitive-text-animator-demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for thinkitive-text-animator-demo
	#pod 'thinkitive-text-animator', '1.2'
	pod 'thinkitive-text-animator', :path => '../'


end
